---
title: "Assessing the susceptibility of celiac disease by polygenic risk scores: analysis of a population-based cohort, the HUNT study."
author: 	Mohammad Sayeef Alam, Laurent F Thomas, Ben Brumpton, Kristian Hveem, Knut E A Lundin, Sebo Withoff, Iris H Jonkers, Ludvig M Sollid, Rebecka Hjort, Eivind Ness Jensen
date: 6 September, 2024
format: html
categories: [Poster, PRS, Celiac, Genetics, Gastrointestinal disease]
toc: false
---

<a href="files/ICDS2024_Poster.pdf" target="_blank" style="background-color: #009000; color: white; padding: 6px 12px; text-decoration: none; border-radius: 4px;"> View poster </a>

## Conference name

### International Coeliac Disease Symposium (ICDS)

## Conference Venue:

*Sheffield, UK*

## Abstract

**Introduction:**  Despite diagnostic advances in celiac disease (CeD), many patients remain undiagnosed. CeD has well established genetic risk factors in the leukocyte antigen (HLA) loci. The goal of the study was to provide susceptibility estimates for CeD subgroups using polygenic risk score (PRS) beyond the HLA loci.

**Methods:** In the population-based HUNT study in Norway, 52,588 adults underwent CeD screening via serology with diagnosis confirmed by histology (revealing 465 incident [Marsh 3] and 230 potential [Marsh 1/2] cases). Additionally, 377 known CeD cases were identified from medical registries. We reproduced a previously published PRS of CeD (228 SNPs) using the PRS-cs tool. All analysis were adjusted for age, sex, genotyping batch and 20 principal components.

**Results:** The PRS could effectively distinguish between incident and prevalent cases from controls, with area under receiver operating characteristic curves at 83.8% and 83.5%, respectively, superior to potential cases (68.8%). For every standard deviation increase in the PRS, the odds increased 3.4-times (95% confidence interval [CI] 3.1-3.8) for confirmed (incident and prevalent) and 1.8-times (CI 1.6-2.1) for potential cases. Individuals in the top vs remaining decile of the PRS had 8.4-times (CI 7.3-9.7) higher odds of CeD. The proportion of variation explained by the PRS was 20.9% (CI 17.2%-25.6%) from HLA and 1% (CI 0.2%-2.3%) from non-HLA. 

**Conclusions:**  Incorporating non-HLA variants slightly enhanced identification of CeD beyond HLA variants alone, highlighting the potential of genetic risk stratification, integrating both HLA and non-HLA variants to pinpoint high-risk individuals.

*Keywords:* **polygenic**, **symptoms**, **PRS**, **onset**, **genetic**, **autoimmune**
