---
title: "The IRX1 locus is associated with celiac disease: results from a screened population-based cohort, the HUNT study."
author: 	Mohammad Sayeef Alam, Laurent F Thomas, Ben Brumpton, Kristian Hveem, Knut E A Lundin, Sebo Withoff, Iris H Jonkers, Ludvig M Sollid, Rebecka Hjort, Eivind Ness Jensen
date: 9 September, 2024
format: html
categories: [Poster, GWAS, Celiac, Genetics, Gastrointestinal disease]
toc: false
---

<a href="files/NCFH2024_Poster.pdf" target="_blank" style="background-color: #009000; color: white; padding: 6px 12px; text-decoration: none; border-radius: 4px;"> View poster </a>

## Conference name

### The Nordic Conference on Future Health

## Conference Venue:

*Trondheim, Norway*

## Abstract

**Introduction:** Previous studies have discovered genetic loci associated with celiac disease (CeD), within both the human leukocyte antigen (HLA) and the non-HLA region. Yet, half of the genetic variation remains unexplained. This study aims to investigate novel associations with CeD taking advantage of a screened population and mitigating selection-bias from prior case-control studies. 

**Methods:** Utilizing data from the HUNT study in Norway, we screened 52,358 adults (>20 years) for CeD using serology, identifying 465 incident biopsy-confirmed cases. Additionally, 377 prevalent cases were identified through hospital journal searches. Genotyping of 373,185 SNPs was performed using four Illumina HumanCoreExome arrays. Imputation using the Haplotype Reference Consortium panel, resulted in approximately 24.9 million variants, post quality control. A genome-wide association study was performed using SAIGE, and functional mapping and pathway enrichment analysis was conducted using FUMA.

**Results:** Five novel SNPs out of 6 independent associations reached genome wide significance ($P≤5E-08$)  having minor allele count greater than 10. *EML6*, *BCL11A*, *ABCA12*, *LRFN2*, *MED13*, *IRX1* are the loci respectively. Around 50 of over 80 loci identified in previous GWASs were replicated in our data, with *REL*, *ASHA2*, *IL18RAP*, *IL18R1*, *IL18RL1*, *IL18RL2*, *LPP*, *PFKFB3*, *PRKCQ*, *CIITA*, *SOCS1*, and *CLEC16A* reaching suggestive significance levels ($5E-08≤P≤5E-06$).

**Conclusion:** The strongest evidence for an association was observed at *IRX1*, warranting further studies to validate this finding. Notably, the *IRX1* loci has also been associated with other autoimmune diseases such as rheumatoid arthritis.

*Keywords:* **celiac**, **gluten**, **non-HLA**, **autoimmune**, **GWAS**.
